### ISSUE TITLE
Plugin not load

### ISSUE THREAD

**Issue by th1ks** [juliarn/NPC-Lib#117]
hello, I wrote a little code for the NPC, but the plugin does not load and gives this error:
`java.lang.NoClassDefFoundError: com/github/juliarn/npclib/bukkit/BukkitPlatform
        at ru.theahks.tgamelogic.Commands.NPCCommand.<init>(NPCCommand.java:30) ~[tGameLogic-1.0.jar:?]
        at ru.theahks.tgamelogic.EssentialsManager.setupCommands(EssentialsManager.java:98) ~[tGameLogic-1.0.jar:?]
        at ru.theahks.tgamelogic.EssentialsManager.<init>(EssentialsManager.java:42) ~[tGameLogic-1.0.jar:?]
        at ru.theahks.tgamelogic.TGameLogic.initEssentials(TGameLogic.java:26) ~[tGameLogic-1.0.jar:?]
        at ru.theahks.tgamelogic.TGameLogic.onEnable(TGameLogic.java:31) ~[tGameLogic-1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:577) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.github.juliarn.npclib.bukkit.BukkitPlatform
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 17 more`
Do I need to install separate plugins on the server and where can I get them?
ProtocolLib version: **5.1.0**

**Comment by derklaro** [comment]
You need to shade this lib into your plugin

**Comment by th1ks** [comment]
I added the library and ProtocolLib, but the error is the same.
implementation 'io.github.juliarn:npc-lib-bukkit:3.0.0-beta6'

**Comment by derklaro** [comment]
But did you shade the lib into your plugin using the shadow plugin? https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow

**Comment by th1ks** [comment]
No, I didn't know about it, I'll try it tomorrow. At the moment I have a night

**Comment by theahks** [comment]
no, it didn't help. This is what my looks like gradle.build
`buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "com.github.johnrengelman:shadow:8.1.1"
    }
}

plugins {
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id 'java'
}`

**Comment by theahks** [comment]
Yes, it helped. Please tell me how to create the first NPC or install animation for him?
