### ISSUE TITLE
npc create error

### ISSUE THREAD

**Issue by KKW557** [juliarn/NPC-Lib#124]
```java
Npc<World, Player, ItemStack, Plugin> npc = PLATFORM.newNpcBuilder()
            .profile(Profile.resolved("name", UUID.randomUUID()))
            .position(BukkitPlatformUtil.positionFromBukkitModern(loc))
            .buildAndTrack();
```
error:
```
Could not pass event PlayerJoinEvent to MW78Lobby v1.0-SNAPSHOT
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/EnumWrappers$PlayerInfoAction
        at com.github.juliarn.npclib.bukkit.protocol.BukkitProtocolAdapter.packetAdapter(BukkitProtocolAdapter.java:44) ~[?:?]
        at com.github.juliarn.npclib.bukkit.BukkitPlatform.prepareBuild(BukkitPlatform.java:78) ~[?:?]
        at com.github.juliarn.npclib.common.platform.CommonPlatformBuilder.build(CommonPlatformBuilder.java:133) ~[?:?]
        at MW78Lobby-1.0-SNAPSHOT.jar/icu.suc.kevin557.mw78lobby.NPC.<clinit>(NPC.java:17) ~[MW78Lobby-1.0-SNAPSHOT.jar:?]
        at MW78Lobby-1.0-SNAPSHOT.jar/icu.suc.kevin557.mw78lobby.GlobalListener.onPlayerJoin(GlobalListener.java:22) ~[MW78Lobby-1.0-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor20.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-109-5a5035b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-109-5a5035b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-109-5a5035b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:173) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1536) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1513) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1506) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1465) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1472) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1317) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-109-5a5035b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.wrappers.EnumWrappers$PlayerInfoAction
        at io.papermc.paper.plugin.entrypoint.classloader.BytecodeModifyingURLClassLoader.findClass(BytecodeModifyingURLClassLoader.java:75) ~[paper-1.21.jar:1.21-109-5a5035b]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 31 more
```

Paper-1.21-109
ProtocolLib v5.3.0-SNAPSHOT-723

**Comment by derklaro** [comment]
Is your plugin depending on ProtocolLib? I'm not sure how the new paper plugin loading works exactly, but it looks like the plugin is available but your plugin has no access to the classes in ProtocolLib.
