### ISSUE TITLE
Exception in thread

### ISSUE THREAD

**Issue by Angxstupst** [juliarn/NPC-Lib#40]
[19:42:37 WARN]: Exception in thread "Craft Scheduler Thread - 40"
[Lobby-1][19:42:37 WARN]: org.apache.commons.lang.UnhandledException: Plugin Lobby v1.0.6 generated an exception while executing task 8
[Lobby-1]       at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
[Lobby-1]       at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[Lobby-1]       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[Lobby-1]       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[Lobby-1]       at java.lang.Thread.run(Thread.java:748)
[Lobby-1]Caused by: java.lang.LinkageError: com/comphenix/protocol/wrappers/EnumWrappers$NativeGameMode
[Lobby-1]       at com.github.juliarn.npc.modifier.VisibilityModifier.queuePlayerListChange(VisibilityModifier.java:55)
[Lobby-1]       at com.github.juliarn.npc.NPC.hide(NPC.java:114)
[Lobby-1]       at com.github.juliarn.npc.NPCPool.lambda$npcTick$1(NPCPool.java:171)
[Lobby-1]       at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[Lobby-1]       at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[Lobby-1]       ... 4 more

**Comment by juliarn** [comment]
Hey, are you running this on a OpenJ9 JVM?

**Comment by Angxstupst** [comment]
It runs on Java 8 & Debian10 (Buster). Root Server

**Comment by juliarn** [comment]
Can you show the output of `java -version`?

**Comment by Angxstupst** [comment]
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

**Comment by juliarn** [comment]
You did not shade ProtocolLib in your Plugin, right?

**Comment by Angxstupst** [comment]
I don't think

**Comment by Angxstupst** [comment]
I shade my plugin with this:

```
<build>
        <sourceDirectory>${basedir}/src/main/java/</sourceDirectory>
        <!-- Resources -->
        <resources>
            <resource>
                <targetPath>.</targetPath>
                <filtering>true</filtering>
                <directory>${basedir}/src/main/resources/</directory>
            </resource>
        </resources>
        <plugins>
            <!-- JAR creation plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <!-- Shading -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                    <shadedArtifactAttached>true</shadedArtifactAttached>
                </configuration>
            </plugin>
        </plugins>
    </build>

```

@juliarn

**Comment by Angxstupst** [comment]
Here is my code: https://github.com/Angxstupst/NPC

**Comment by juliarn** [comment]
You actually shading ProtocolLib, add ``<scope>provided</scope>`` to the dependency.

**Comment by Angxstupst** [comment]
I add ``<scope>provided</scope>`` to the dependency. The error still comming.

```java.lang.NoSuchMethodException: java.util.Collections$SingletonList.<init>()
[Lobby-1][02:57:00 WARN]:       at java.lang.Class.getConstructor0(Class.java:3082)
[Lobby-1][02:57:00 WARN]:       at java.lang.Class.getConstructor(Class.java:1825)
[Lobby-1][02:57:00 WARN]:       at com.comphenix.protocol.wrappers.BukkitConverters.getGenericList(BukkitConverters.java:277)
[Lobby-1][02:57:00 WARN]:       at com.comphenix.protocol.wrappers.BukkitConverters.access$100(BukkitConverters.java:88)
[Lobby-1][02:57:00 WARN]:       at com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:367)
[Lobby-1][02:57:00 WARN]:       at com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:359)
[Lobby-1][02:57:00 WARN]:       at com.comphenix.protocol.wrappers.Converters$1.getGeneric(Converters.java:48)
[Lobby-1][02:57:00 WARN]:       at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:372)
[Lobby-1][02:57:00 WARN]:       at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345)
[Lobby-1][02:57:00 WARN]:       at com.github.juliarn.npc.modifier.VisibilityModifier.queuePlayerListChange(VisibilityModifier.java:60)
[Lobby-1][02:57:00 WARN]:       at com.github.juliarn.npc.NPC.show(NPC.java:86)
[Lobby-1][02:57:00 WARN]:       at com.github.juliarn.npc.NPCPool.lambda$npcTick$1(NPCPool.java:173)
[Lobby-1][02:57:00 WARN]:       at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[Lobby-1][02:57:00 WARN]:       at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[Lobby-1][02:57:00 WARN]:       at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[Lobby-1][02:57:00 WARN]:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[Lobby-1][02:57:00 WARN]:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[Lobby-1][02:57:00 WARN]:       at java.lang.Thread.run(Thread.java:748)
[Lobby-1][02:57:14 INFO]: Angxstupst lost connection: Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer
```

**Comment by juliarn** [comment]
Thats only a warning, update ProtocolLib, it was hidden in a newer version.
