### ISSUE TITLE
Weird Warning

### ISSUE THREAD

**Issue by DolphinGamerYT** [juliarn/NPC-Lib#43]
Hey, so just doing a plugin with this library, all worked great, NPC spawned with it's gameprofile properties, but I just got this weird warning (not ERR), that says something about show stuff? I'm using the development release

Error:
`[03:40:42 WARN]: java.lang.NoSuchMethodException: java.util.Collections$SingletonList.<init>()
[03:40:42 WARN]:        at java.base/java.lang.Class.getConstructor0(Class.java:3517)
[03:40:42 WARN]:        at java.base/java.lang.Class.getConstructor(Class.java:2238)
[03:40:42 WARN]:        at com.comphenix.protocol.wrappers.BukkitConverters.getGenericList(BukkitConverters.java:277)
[03:40:42 WARN]:        at com.comphenix.protocol.wrappers.BukkitConverters.access$100(BukkitConverters.java:88)
[03:40:42 WARN]:        at com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:367)
[03:40:42 WARN]:        at com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:359)
[03:40:42 WARN]:        at com.comphenix.protocol.wrappers.Converters$1.getGeneric(Converters.java:48)
[03:40:42 WARN]:        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:372)
[03:40:42 WARN]:        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345)
[03:40:42 WARN]:        at com.dolphln.npc.modifier.VisibilityModifier.queuePlayerListChange(VisibilityModifier.java:59)
[03:40:42 WARN]:        at com.dolphln.npc.NPC.show(NPC.java:95)
[03:40:42 WARN]:        at com.dolphln.npc.NPCPool.lambda$npcTick$1(NPCPool.java:208)
[03:40:42 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[03:40:42 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[03:40:42 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[03:40:42 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[03:40:42 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[03:40:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)`

I'm gonna be honest, I didn't really see if it has something to do with my plugin, but I thought I better post it here.

Edit: Also using purpur 1.17.1`> version
[03:46:13 INFO]: Checking version, please wait...
[03:46:14 INFO]: This server is running Purpur version git-Purpur-1287 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 01b35a2 on ver/1.17.1)
[03:46:14 INFO]: You are running the latest version
[03:46:14 INFO]: Previous version: git-Purpur-1206 (MC: 1.17)`

**Comment by juliarn** [comment]
Hey, ProtocolLib seems to have broken something internally, but I changed something that it should work now. Thanks for the report.
