### ISSUE TITLE
java.lang.NoClassDefFoundError: com/github/juliarn/npc/NPCPool

### ISSUE THREAD

**Issue by binda02** [juliarn/NPC-Lib#49]
[12.09 12:47:15.822] INFO: [Skyfall-1] [12:47:15 ERROR]: Error occurred while enabling 4Bedwars v1.0 (Is it up to date?)
[12.09 12:47:15.822] INFO: [Skyfall-1] java.lang.NoClassDefFoundError: com/github/juliarn/npc/NPCPool
[12.09 12:47:15.822] INFO: [Skyfall-1]  at de.binda.Bedwars.Npcs.ShopNpc.<init>(ShopNpc.java:32) ~[4Bedwars.jar:?]
[12.09 12:47:15.822] INFO: [Skyfall-1]  at de.binda.Bedwars.Bedwars.onEnable(Bedwars.java:74) ~[4Bedwars.jar:?]
[12.09 12:47:15.822] INFO: [Skyfall-1]  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper.jar:git-Paper-249]
[12.09 12:47:15.822] INFO: [Skyfall-1]  at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper.jar:git-Paper-249]
[12.09 12:47:15.822] INFO: [Skyfall-1]  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper.jar:git-Paper-249]
[12.09 12:47:15.822] INFO: [Skyfall-1]  at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535) ~[paper.jar:git-Paper-249]
[12.09 12:47:15.822] INFO: [Skyfall-1]  at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449) ~[paper.jar:git-Paper-249]
[12.09 12:47:15.822] INFO: [Skyfall-1]  at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725) ~[paper.jar:git-Paper-249]
[12.09 12:47:15.822] INFO: [Skyfall-1]  at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306) ~[paper.jar:git-Paper-249]
[12.09 12:47:15.822] INFO: [Skyfall-1]  at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1212) ~[paper.jar:git-Paper-249]
[12.09 12:47:15.822] INFO: [Skyfall-1]  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper.jar:git-Paper-249]
[12.09 12:47:15.822] INFO: [Skyfall-1]  at java.lang.Thread.run(Thread.java:831) [?:?]
[12.09 12:47:15.822] INFO: [Skyfall-1] Caused by: java.lang.ClassNotFoundException: com.github.juliarn.npc.NPCPool
[12.09 12:47:15.822] INFO: [Skyfall-1]  at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[paper.jar:git-Paper-249]
[12.09 12:47:15.822] INFO: [Skyfall-1]  at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper.jar:git-Paper-249]
[12.09 12:47:15.822] INFO: [Skyfall-1]  at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
[12.09 12:47:15.822] INFO: [Skyfall-1]  ... 12 more

**Comment by juliarn** [comment]
Hey, you have to shade the Lib inside your Plugin.

**Comment by binda02** [comment]
How ?

**Comment by juliarn** [comment]
With the maven shade plugin for example or the gradle shadow plugin.

**Comment by binda02** [comment]
Completed. But now I have this mistake.

[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: java.lang.NoSuchMethodException: java.util.Collections$SingletonList.<init>()
[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: 	at java.base/java.lang.Class.getConstructor0(Class.java:3517)
[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: 	at java.base/java.lang.Class.getConstructor(Class.java:2238)
[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.wrappers.BukkitConverters.getGenericList(BukkitConverters.java:277)
[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.wrappers.BukkitConverters.access$100(BukkitConverters.java:88)
[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:367)
[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:359)
[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.wrappers.Converters$1.getGeneric(Converters.java:48)
[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:372)
[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345)
[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: 	at 4Bedwars-1.0-SNAPSHOT-shaded.jar//com.github.juliarn.npc.modifier.VisibilityModifier.queuePlayerListChange(VisibilityModifier.java:60)
[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: 	at 4Bedwars-1.0-SNAPSHOT-shaded.jar//com.github.juliarn.npc.NPC.show(NPC.java:86)
[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: 	at 4Bedwars-1.0-SNAPSHOT-shaded.jar//com.github.juliarn.npc.NPCPool.lambda$npcTick$1(NPCPool.java:173)
[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[19:09:02] [Craft Scheduler Thread - 1 - 4Bedwars/WARN]: [4Bedwars] Plugin 4Bedwars v1.0 generated an exception while executing task 14
java.lang.RuntimeException: Failed to construct PlayerInfoData.
	at com.comphenix.protocol.wrappers.PlayerInfoData$1.getGeneric(PlayerInfoData.java:129) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.PlayerInfoData$1.getGeneric(PlayerInfoData.java:96) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.BukkitConverters.getGenericList(BukkitConverters.java:300) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.BukkitConverters.access$100(BukkitConverters.java:88) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:367) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:359) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.Converters$1.getGeneric(Converters.java:48) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:372) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[ProtocolLib.jar:?]
	at com.github.juliarn.npc.modifier.VisibilityModifier.queuePlayerListChange(VisibilityModifier.java:60) ~[4Bedwars-1.0-SNAPSHOT-shaded.jar:?]
	at com.github.juliarn.npc.NPC.show(NPC.java:86) ~[4Bedwars-1.0-SNAPSHOT-shaded.jar:?]
	at com.github.juliarn.npc.NPCPool.lambda$npcTick$1(NPCPool.java:173) ~[4Bedwars-1.0-SNAPSHOT-shaded.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper.jar:git-Paper-249]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [paper.jar:git-Paper-249]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [paper.jar:git-Paper-249]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant net.minecraft.world.level.EnumGamemode.NOT_SET
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getGeneric(EnumWrappers.java:811) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getGeneric(EnumWrappers.java:792) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.PlayerInfoData$1.getGeneric(PlayerInfoData.java:120) ~[ProtocolLib.jar:?]
	... 17 more

**Comment by juliarn** [comment]
Are you sure that you have the latest ProtocolLib and NPCLib versions?

**Comment by binda02** [comment]
Sure. The newest ProtocolLib and NpcLib 2.5

**Comment by juliarn** [comment]
Try ``development-snapshot`` as version, 1.17 support is not included in 2.5 afaik.

**Comment by binda02** [comment]
its working

**Comment by mindcubr** [comment]
Hey guys I don't quite understand how you got the library implemented.
I still got NoClassDefFoundError, even if the plugin installed.

**Comment by derklaro** [comment]
👍
