### ISSUE TITLE
 java.lang.NoSuchMethodException On Player Join

### ISSUE THREAD

**Issue by CraftingDragon007** [juliarn/NPC-Lib#57]
Every Time a player logs on this Exception gets thrown.
[15:36:38 WARN]: java.lang.NoSuchMethodException: java.util.Collections$SingletonList.<init>()
[15:36:38 WARN]:        at java.base/java.lang.Class.getConstructor0(Class.java:3585)
[15:36:38 WARN]:        at java.base/java.lang.Class.getConstructor(Class.java:2271)
[15:36:38 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.wrappers.BukkitConverters.getGenericList(BukkitConverters.java:277)
[15:36:38 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.wrappers.BukkitConverters.access$100(BukkitConverters.java:88)
[15:36:38 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:367)
[15:36:38 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:359)
[15:36:38 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.wrappers.Converters$1.getGeneric(Converters.java:48)
[15:36:38 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:372)
[15:36:38 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345)
[15:36:38 WARN]:        at wirtschaft-1.4-all.jar//com.github.juliarn.npc.modifier.EquipmentModifier.lambda$queue$0(EquipmentModifier.java:104)
[15:36:38 WARN]:        at wirtschaft-1.4-all.jar//com.github.juliarn.npc.modifier.NPCModifier.queueInstantly(NPCModifier.java:72)
[15:36:38 WARN]:        at wirtschaft-1.4-all.jar//com.github.juliarn.npc.modifier.EquipmentModifier.queue(EquipmentModifier.java:82)
[15:36:38 WARN]:        at wirtschaft-1.4-all.jar//com.github.juliarn.npc.modifier.EquipmentModifier.queue(EquipmentModifier.java:122)
[15:36:38 WARN]:        at wirtschaft-1.4-all.jar//net.weareproud.wirtschaft.npc.NPCManager.lambda$createSpawnNPC$0(NPCManager.java:55)
[15:36:38 WARN]:        at wirtschaft-1.4-all.jar//com.github.juliarn.npc.NPC.lambda$show$1(NPC.java:123)
[15:36:38 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:36:38 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[15:36:38 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1591)
[15:36:38 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:528)
[15:36:38 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1507)
[15:36:38 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1300)
[15:36:38 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[15:36:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by juliarn** [comment]
Hey, please try to update ProtocolLib, the issue should be resolved then.
