### ISSUE TITLE
Cannot spawn NPC

### ISSUE THREAD

**Issue by zAlyson** [juliarn/npc-lib#60]
```
[18:45:01 WARN]: Exception in thread "Craft Scheduler Thread - 2" 
[18:45:01 WARN]: org.apache.commons.lang.UnhandledException: Plugin AspectEconomy v1.0.0-SNAPSHOT generated an exception while executing task 10
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.LinkageError: loader org.bukkit.plugin.java.PluginClassLoader @2dc96b52 attempted duplicate class definition for com.comphenix.protocol.events.PacketContainer. (com.comphenix.protocol.events.PacketContainer is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @2dc96b52, parent loader 'app')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:103)
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:193)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:99)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:88)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.github.juliarn.npc.modifier.VisibilityModifier.queuePlayerListChange(VisibilityModifier.java:53)
	at com.github.juliarn.npc.NPC.show(NPC.java:119)
	at com.github.juliarn.npc.NPCPool.lambda$npcTick$1(NPCPool.java:217)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
```

Every time I try to spawn a NPC, I get this error.

**Comment by wasn325** [comment]
maybe try to update protocollib and check if there a multiple versions loaded (example: protocollib standalone and shaded into another plugin)

**Comment by zAlyson** [comment]
@wasn325 I already did that and there's no protocollib shaded into another plugin. The odd is, sometimes it spawns with no errors. If I restart the server and try to spawn the npc, it may spawn or not spawn.
