### ISSUE TITLE
Error in console + other problem

### ISSUE THREAD

**Issue by sqcred** [juliarn/NPC-Lib#69]
my console gets spammed with this error

java.lang.NoClassDefFoundError: com/github/juliarn/npc/event/PlayerNPCHideEvent$Reason
        at com.github.juliarn.npc.NPCPool.lambda$npcTick$1(NPCPool.java:215) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: com.github.juliarn.npc.event.PlayerNPCHideEvent$Reason
        ... 6 more
[15:06:30] [Craft Scheduler Thread - 0/WARN]: [Magic] Plugin Magic v1.0 generated an exception while executing task 5
java.lang.NoClassDefFoundError: com/github/juliarn/npc/event/PlayerNPCHideEvent$Reason
        at com.github.juliarn.npc.NPCPool.lambda$npcTick$1(NPCPool.java:215) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: com.github.juliarn.npc.event.PlayerNPCHideEvent$Reason

Also the interact event does not work after rejoin

**Comment by sqcred** [comment]
well i fixed the first problem but not the second one

**Comment by dandan2611** [comment]
Did you shadow the library into the packaged jar?
