### ISSUE TITLE
Im getting this a couple seconds after loading the NPC/Plugin

### ISSUE THREAD

**Issue by typicalsmc** [juliarn/NPC-Lib#71]
[05:17:54] [Craft Scheduler Thread - 30 - SimpNPC/WARN]: [SimpNPC] Plugin SimpNPC v1.0 generated an exception while executing task 9414
java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.pipeline()" because "channel" is null
	at com.comphenix.protocol.injector.netty.ChannelInjector.findChannelHandler(ChannelInjector.java:932) ~[ProtocolLib (4).jar:?]
	at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:93) ~[ProtocolLib (4).jar:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:411) ~[ProtocolLib (4).jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:733) ~[ProtocolLib (4).jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:687) ~[ProtocolLib (4).jar:?]
	at com.github.juliarn.npc.modifier.NPCModifier.lambda$1(NPCModifier.java:90) ~[SimpNPC-1.0.jar:?]
	at java.util.Arrays$ArrayList.forEach(Arrays.java:4204) ~[?:?]
	at com.github.juliarn.npc.modifier.NPCModifier.send(NPCModifier.java:88) ~[SimpNPC-1.0.jar:?]
	at com.github.juliarn.npc.modifier.NPCModifier.send(NPCModifier.java:104) ~[SimpNPC-1.0.jar:?]
	at com.github.juliarn.npc.NPC.hide(NPC.java:192) ~[SimpNPC-1.0.jar:?]
	at com.github.juliarn.npc.NPCPool.lambda$1(NPCPool.java:211) ~[SimpNPC-1.0.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[simpmcpaper-1.18.1.jar:git-SimpMCPaper-"add22dc"]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[simpmcpaper-1.18.1.jar:git-SimpMCPaper-"add22dc"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[simpmcpaper-1.18.1.jar:git-SimpMCPaper-"add22dc"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by derklaro** [comment]
Hi, I am pretty sure this is not a NPC-Lib Issue, I guess that either ProtocolLib is outdated or your "SimpPaper" is changing fields which shouldn't be changed.

**Comment by typicalsmc** [comment]
hm, ok

**Comment by derklaro** [comment]
Closing due to inactivity.
