### ISSUE TITLE
Player Crashing and NPE

### ISSUE THREAD

**Issue by The60th** [juliarn/NPC-Lib#75]
Happens when I'm near a NPC that has their name set to that of an online player

My currently Protocollib version is: 4.8.0

[16:09:53 ERROR]: java.lang.NullPointerException
[16:09:53 WARN]: java.lang.NullPointerException
[16:09:53 WARN]:        at net.minecraft.server.v1_16_R3.PacketDataSerializer.a(PacketDataSerializer.java:390)
[16:09:53 WARN]:        at net.minecraft.server.v1_16_R3.PacketDataSerializer.a(PacketDataSerializer.java:385)
[16:09:53 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayOutPlayerInfo.b(SourceFile:104)
[16:09:53 WARN]:        at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:46)
[16:09:53 WARN]:        at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:15)
[16:09:53 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
[16:09:53 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:09:53 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[16:09:53 WARN]:        at com.viaversion.viaversion.util.PipelineUtil.callEncode(PipelineUtil.java:93)
[16:09:53 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:71)
[16:09:53 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
[16:09:53 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:09:53 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[16:09:53 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:531)
[16:09:53 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:72)
[16:09:53 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:271)
[16:09:53 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[16:09:53 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:277)
[16:09:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:09:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:09:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:09:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:09:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:697)
[16:09:53 WARN]:        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
[16:09:53 WARN]:        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:284)
[16:09:53 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.write(ChannelProxy.java:312)
[16:09:53 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager.lambda$writePacket$11(NetworkManager.java:485)
[16:09:53 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:354)
[16:09:53 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[16:09:53 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[16:09:53 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[16:09:53 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[16:09:53 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:09:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[16:09:53 INFO]: the60th lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerExcept

**Comment by derklaro** [comment]
The most interesting part of the stack trace is cut off (above the first line)

**Comment by The60th** [comment]
Resent
https://gist.github.com/The60th/d4406106f889bc7c0d4f2f2ded9eb40e

Let me know if there is any other debugging information that would be helpful
