### ISSUE TITLE
NPC Interact Event Error

### ISSUE THREAD

**Issue by RemineHD** [juliarn/NPC-Lib#81]
[19:56:55 ERROR]: Village > [19:56:55 ERROR] [Minecraft]: [VillageCore] Unhandled exception occured in onPacketReceiving(PacketEvent) for VillageCore
[19:56:55 ERROR]: Village > java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedEnumEntityUseAction
[19:56:55 ERROR]: Village >     at com.comphenix.protocol.events.AbstractStructure.getEnumEntityUseActions(AbstractStructure.java:614) ~[ProtocolLib.jar:4.8.0]
[19:56:55 ERROR]: Village >     at com.github.juliarn.npc.NPCPool$1.onPacketReceiving(NPCPool.java:161) ~[VillageCore-1.0-SNAPSHOT-shaded.jar:?]
[19:56:55 ERROR]: Village >     at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.8.0]
[19:56:55 ERROR]: Village >     at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.8.0]
[19:56:55 ERROR]: Village >     at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) [ProtocolLib.jar:4.8.0]
[19:56:55 ERROR]: Village >     at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) [ProtocolLib.jar:4.8.0]
[19:56:55 ERROR]: Village >     at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) [ProtocolLib.jar:4.8.0]
[19:56:55 ERROR]: Village >     at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) [ProtocolLib.jar:4.8.0]
[19:56:55 ERROR]: Village >     at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:600) [ProtocolLib.jar:4.8.0]
[19:56:55 ERROR]: Village >     at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292) [ProtocolLib.jar:4.8.0]
[19:56:55 ERROR]: Village >     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar%2331!/:4.1.68.Final]
[19:56:55 ERROR]: Village >     at java.lang.Thread.run(Thread.java:833) [?:?]
[19:56:55 ERROR]: Village > [19:56:55 ERROR] [Minecraft]: Parameters:
[19:56:55 ERROR]: Village >   net.minecraft.network.protocol.game.ServerboundInteractPacket@7daec04e[
[19:56:55 ERROR]: Village >     f_134030_=612957245
[19:56:55 ERROR]: Village >     f_134031_=net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction@25ca88ec
[19:56:55 ERROR]: Village >     f_134034_=false
[19:56:55 ERROR]: Village >   ]
[19:56:55 ERROR]: Village >

(Yes, we have ProtocolLib installed, and dependency added in both plugin.yml and pom.xml)

**Comment by derklaro** [comment]
Seems like your ProtocolLib versions is outdated, try bumping to v5: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by RemineHD** [comment]
Umm still not working, i have to do a Maven Clean before compilling in order to make it work, seems like a wired Maven Error
