### ISSUE TITLE
NoSuchFieldError 

### ISSUE THREAD

**Issue by plytki** [juliarn/NPC-Lib#95]
I have compiled in lib into my jar file and when launching the plugin I get this error:
```
[20:03:44 ERROR]: Error occurred while enabling CryptoMine v2.0-SNAPSHOT (Is it up to date?)
java.lang.NoSuchFieldError: UPDATE_LISTED
        at com.github.juliarn.npclib.bukkit.protocol.ProtocolLibPacketAdapter.<clinit>(ProtocolLibPacketAdapter.java:110) ~[cryptomine-2.0-SNAPSHOT.jar:?]
        at com.github.juliarn.npclib.bukkit.protocol.BukkitProtocolAdapter.packetAdapter(BukkitProtocolAdapter.java:44) ~[cryptomine-2.0-SNAPSHOT.jar:?]
        at com.github.juliarn.npclib.bukkit.BukkitPlatform.prepareBuild(BukkitPlatform.java:72) ~[cryptomine-2.0-SNAPSHOT.jar:?]
        at com.github.juliarn.npclib.common.platform.CommonPlatformBuilder.build(CommonPlatformBuilder.java:139) ~[cryptomine-2.0-SNAPSHOT.jar:?]
        at dev.plytki.cryptomine.world.npc.NPCs.<init>(NPCs.java:45) ~[cryptomine-2.0-SNAPSHOT.jar:?]
        at dev.plytki.cryptomine.CryptoMine.onEnable(CryptoMine.java:145) ~[cryptomine-2.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

This is my code:
![image](https://user-images.githubusercontent.com/53957038/219969673-70fc3916-247d-40f8-bb64-ad9df29c76bc.png)

The library I'm currently using:
![image](https://user-images.githubusercontent.com/53957038/219969764-d934a79f-eb06-41c7-b31c-b0a310db7742.png)

**Comment by derklaro** [comment]
If you want to use ProtocolLib make sure you use the latest dev version from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by plytki** [comment]
Thank you! That worked! :)
