### ISSUE TITLE
Packet NullPointerException

### ISSUE THREAD

**Issue by plytki** [juliarn/NPC-Lib#96]
What's the issue? I don't even see any trace of my code.
```
[23:18:02 ERROR]: Could not pass event PlayerMoveEvent to CryptoMine v2.0-SNAPSHOT
java.lang.NullPointerException: Unable to create packet instance for class class net.minecraft.network.protocol.game.PacketPlayOutEntityHeadRotation
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at com.comphenix.protocol.injector.StructureCache.lambda$newPacket$2(StructureCache.java:97) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:101) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:111) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:117) ~[ProtocolLib.jar:?]
        at com.github.juliarn.npclib.bukkit.protocol.ProtocolLibPacketAdapter.lambda$createRotationPacket$8(ProtocolLibPacketAdapter.java:363) ~[cryptomine-2.0-SNAPSHOT.jar:?]
        at com.github.juliarn.npclib.api.protocol.DefaultNpcSpecificOutboundPacket.schedule(DefaultNpcSpecificOutboundPacket.java:57) ~[cryptomine-2.0-SNAPSHOT.jar:?]
        at com.github.juliarn.npclib.bukkit.BukkitActionController.handleMove(BukkitActionController.java:155) ~[cryptomine-2.0-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor95.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-388]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1505) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:88) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by vytskalt** [comment]
I also sometimes get this

**Comment by derklaro** [comment]
Just tested this with 1.18.2 and ProtocolLib - I cannot reproduce this issue...
![image](https://user-images.githubusercontent.com/40468651/220077025-320c2814-8984-40c5-84ea-ad4b7b2eb578.png)

**Comment by plytki** [comment]
I switched to 1.8 instead of 1.18.2 and I don't get this issue anymore. Issue still not solved. I don't know how to reproduce it either. I think it's random.
